import type { Metadata } from "next";
import { LegalPage } from "@/components/site/legal-page";
import { STUDIO_EMAIL } from "@/lib/studio";

export const metadata: Metadata = {
  title: "Privacy",
  description: "What this site does and does not collect.",
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy"
      updated="September 2026"
      clauses={[
        {
          heading: "Analytics, advertising and cookies",
          body: (
            <p>
              This site does not employ analytics, advertising or tracking cookies, and sets no cookies of its own. The
              only data processed is that necessarily generated by hosting and by the embedded showcase previews, each
              described below.
            </p>
          ),
        },
        {
          heading: "The project enquiry form",
          body: (
            <p>
              Information entered into the project enquiry form is held solely within your browser. Selecting “Open
              email draft” populates a message in your own email client; no data is transmitted to us unless and until
              you elect to send that message. Closing the tab discards the information in its entirety.
            </p>
          ),
        },
        {
          heading: "Correspondence",
          body: (
            <p>
              Where you contact us by email, we retain the information you provide — your name, business name, email
              address and the details of your enquiry — for the purposes of responding and preparing a quotation. We do
              not sell, license or otherwise disclose it to third parties, and we do not add you to any mailing list.
              You may request its deletion at any time, and we will comply.
            </p>
          ),
        },
        {
          heading: "Hosting and third-party embeds",
          body: (
            <p>
              This site is served as static files. The host records standard technical request logs, including IP
              address and request time, for the purposes of delivering and securing the pages. The showcase previews on
              the work page are loaded directly from GitHub Pages; requests for those pages are visible to GitHub in the
              same manner as if you had visited them directly.
            </p>
          ),
        },
        {
          heading: "Contact",
          body: (
            <p>
              Enquiries regarding this notice should be directed to{" "}
              <a className="text-ember hover:underline" href={`mailto:${STUDIO_EMAIL}`}>{STUDIO_EMAIL}</a>.
            </p>
          ),
        },
      ]}
    />
  );
}
